pipeline {
    agent any
    
    stages {
        stage('Build') {
            steps {
                script {
                    echo "Build stage"
                }
            }
        }
        
        stage('Checkout') {
            steps {
                script {
                    echo "Checkout stage"
                  
                }
            }
        }
        
        stage('Configure') {
            steps {
                script {
                    echo "Configure stage"
                }
            }
        }
        
        stage('Build Again') {
            steps {
                script {
                    echo "Build stage (again)"
                }
            }
        }
        
        stage('Security Dependency Check') {
            steps {
                script {
                    echo "Security Dependency Check stage"
                }
            }
        }
    }
}